#!/usr/bin/env bash
INSTALL_PYTHON=/usr/bin/python
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit >/dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    # shellcheck disable=SC2016
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
